export const TRANSLATIONS = {
  en: {
    // Navbar
    dashboard: "Dashboard",
    pos: "Sales",
    inventory: "Inventory",
    salesHistory: "Sales History",
    purchaseEntry: "Purchase Entry",
    reports: "Reports",
    upiSettings: "UPI QR Setup",
    shopSettings: "Shop Settings",
    logout: "Log Out",
    welcome: "Welcome",
    
    // Login / Setup
    loginHeading: "DO BILL Barcode Billing System",
    loginSub: "Kanchipuram & Bridal Lehenga Crafts Inventory ERP",
    loginPin: "Cashier PIN / Admin Password",
    loginButton: "Access Terminal",
    incorrectPin: "Incorrect PIN! Please try again.",
    
    // POS
    posTitle: "Point of Sale (POS)",
    scanBarcodePlaceholder: "Scan Barcode or Search Product by Name (F1 for Focus)...",
    searchPlaceholder: "Search Item Name ...",
    cartLabel: "Active Sales Cart",
    emptyCart: "Cart is currently empty. Scan or search items to get started.",
    customerDetails: "Customer Information",
    customerName: "Customer Name",
    customerPhone: "Phone Number",
    customerAddress: "Home Address",
    discount: "Discount (₹)",
    tax: "GST Tax",
    subtotal: "Subtotal",
    taxTotal: "CGST & SGST",
    grandTotal: "Grand Total",
    payable: "Payable",
    cashReceived: "Cash Received (F9)",
    changeDue: "Change Due",
    paymentMode: "Payment Method",
    cash: "Cash (F10)",
    upi: "UPI QR Code",
    holdBill: "Hold Bill",
    checkout: "Finalize & Print GST Invoice",
    receiptTitle: "GST Tax Invoice Preview",
    shortcutHelp: "Keyboard Shortcuts: F1: Focus Barcode | F9: Cash Input | F10: Cash Toggle | DEL: Clear Cart",
    
    // Purchase Entry
    purchaseTitle: "Purchase Order & Inventory Receipt",
    supplierName: "Supplier / Weaver Name",
    supplierPhone: "Supplier Mobile No.",
    invoiceRef: "Purchase Invoice Ref No.",
    addProductToPurchase: "Scan or Add Product to Purchase Receipt",
    addPurchaseHeader: "New Purchase Items Lot",
    purchasePrice: "Purchase (Buy) Price (₹)",
    sellingPrice: "Selling (Retail) Price (₹)",
    qtyToReceive: "Quantity to Receive",
    addPurchaseButton: "Save Purchase & Increment Stock",
    supplierDetails: "Supplier Details",
    invoiceNo: "Invoice Number",
    purchaseDate: "Purchase Date",
    action: "Action",
    clearPurchase: "Clear Receipt",
    totalPurchasedItems: "Total Purchased Items",
    recentPurchases: "Recent Purchases Log",
    purchaseHistory: "Purchase History",
    
    // Inventory
    inventoryTitle: "Product Catalog",
    addNewProduct: "Insert New Saree / Clothing item",
    searchInventory: "Search inventory item by Name, Barcode & Category ...",
    productName: "Item Name",
    brand: "Brand/Weaver",
    category: "Category",
    gstPercent: "GST Rate (%)",
    stockQuantity: "Stock Qty",
    reorderLevel: "Reorder Alert Level",
    unit: "Unit (pcs/meters)",
    actions: "Actions",
    editItem: "Edit Item Record",
    deleteItem: "Delete Item",
    lowStockBadge: "Low Stock Alert",
    regularStock: "Regular Stock",
    barcodeLabel: "Barcode Label Print",
    printBarcode: "Print Label",
    saveProduct: "Save Product",
    cancel: "Cancel",
    
    // Reports
    reportsTitle: "Business Intelligence & Statements",
    startDate: "Start Date",
    endDate: "End Date",
    totalSales: "Total Sales Record",
    revenue: "Total Revenue",
    grossProfit: "Estimated Gross Profit",
    totalBills: "GST Invoices Issued",
    avgOrder: "Avg Order Value",
    dailyTrend: "Daily Sales Movement",
    paymentShare: "Payment Mode Split",
    topSelling: "Best Selling Garments",
    categoryShare: "Category Distribution",
    lowStockReport: "Low Stock Inventory List",
    profitEstimation: "Profit Margin Estimator",
    profitEstimated: "Profit (₹)"
  },
  hi: {
    // Navbar
    dashboard: "डैशबोर्ड",
    pos: "बिक्री (POS)",
    inventory: "स्टॉक सूची",
    salesHistory: "बिक्री इतिहास",
    purchaseEntry: "खरीद प्रविष्टि",
    reports: "रिपोर्ट्स",
    upiSettings: "यूपीआई सेटअप",
    shopSettings: "दुकान सेटिंग्स",
    logout: "लॉग आउट",
    welcome: "स्वागत है",
    
    // Login / Setup
    loginHeading: "DO BILL बारकोड बिलिंग सिस्टम",
    loginSub: "कांजीवरम और ब्राइडल लहंगा क्राफ्ट्स इन्वेंटरी ईआरपी",
    loginPin: "कैशियर पिन / एडमिन पासवर्ड",
    loginButton: "टर्मिनल खोलें",
    incorrectPin: "गलत पिन! कृपया पुनः प्रयास करें।",
    
    // POS
    posTitle: "पॉइंट ऑफ़ सेल (POS)",
    scanBarcodePlaceholder: "बारकोड स्कैन करें या उत्पाद का नाम खोजें (F1 फोकस के लिए)...",
    searchPlaceholder: "आइटम का नाम खोजें ...",
    cartLabel: "सक्रिय बिक्री कार्ट",
    emptyCart: "कार्ट वर्तमान में खाली है। शुरू करने के लिए स्कैन या खोजें।",
    customerDetails: "ग्राहक की जानकारी",
    customerName: "ग्राहक का नाम",
    customerPhone: "फोन नंबर",
    customerAddress: "घर का पता",
    discount: "छूट (₹)",
    tax: "जीएसटी टैक्स",
    subtotal: "उप-योग",
    taxTotal: "सीजीएसटी और एसजीएसटी",
    grandTotal: "कुल योग",
    payable: "देय राशि",
    cashReceived: "नकद प्राप्त हुआ (F9)",
    changeDue: "वापस करने योग्य राशि",
    paymentMode: "भुगतान का प्रकार",
    cash: "नकद (F10)",
    upi: "यूपीआई क्यूआर कोड",
    holdBill: "बिल होल्ड करें",
    checkout: "पूरा करें और जीएसटी चालान प्रिंट करें",
    receiptTitle: "जीएसटी टैक्स चालान पूर्वावलोकन",
    shortcutHelp: "कीबोर्ड शॉर्टकट: F1: फोकस बारकोड | F9: नकद इनपुट | F10: नकद टॉगल | DEL: कार्ट साफ करें",
    
    // Purchase Entry
    purchaseTitle: "खरीद ऑर्डर और स्टॉक प्राप्ति",
    supplierName: "आपूर्तिकर्ता / बुनकर का नाम",
    supplierPhone: "आपूर्तिकर्ता मोबाइल नंबर",
    invoiceRef: "खरीद चालान संदर्भ संख्या",
    addProductToPurchase: "खरीद रसीद में उत्पाद स्कैन या जोड़ें",
    addPurchaseHeader: "नया खरीद आइटम लॉट",
    purchasePrice: "खरीद मूल्य (₹)",
    sellingPrice: "बिक्री मूल्य (₹)",
    qtyToReceive: "प्राप्त करने की मात्रा",
    addPurchaseButton: "खरीद सहेजें और स्टॉक बढ़ाएं",
    supplierDetails: "आपूर्तिकर्ता विवरण",
    invoiceNo: "चालान संख्या",
    purchaseDate: "खरीद तिथि",
    action: "कार्रवाई",
    clearPurchase: "रसीद साफ करें",
    totalPurchasedItems: "कुल खरीदे गए आइटम",
    recentPurchases: "हालिया खरीद लॉग",
    purchaseHistory: "खरीद इतिहास",
    
    // Inventory
    inventoryTitle: "उत्पाद सूची",
    addNewProduct: "नई साड़ी / कपड़ा आइटम जोड़ें",
    searchInventory: "नाम, बारकोड और श्रेणी द्वारा स्टॉक खोजें ...",
    productName: "आइटम का नाम",
    brand: "ब्रांड/बुनकर",
    category: "श्रेणी",
    gstPercent: "जीएसटी दर (%)",
    stockQuantity: "स्टॉक मात्रा",
    reorderLevel: "रीऑर्डर चेतावनी स्तर",
    unit: "इकाई (pcs/meters)",
    actions: "कार्रवाई",
    editItem: "आइटम रिकॉर्ड संपादित करें",
    deleteItem: "आइटम हटाएं",
    lowStockBadge: "कम स्टॉक चेतावनी",
    regularStock: "सामान्य स्टॉक",
    barcodeLabel: "बारकोड लेबल प्रिंट",
    printBarcode: "लेबल प्रिंट करें",
    saveProduct: "उत्पाद सहेजें",
    cancel: "रद्द करें",
    
    // Reports
    reportsTitle: "व्यापार विश्लेषण और रिपोर्ट",
    startDate: "प्रारंभ तिथि",
    endDate: "अंतिम तिथि",
    totalSales: "कुल बिक्री रिकॉर्ड",
    revenue: "कुल राजस्व",
    grossProfit: "अनुमानित सकल लाभ",
    totalBills: "जीएसटी चालान जारी किए गए",
    avgOrder: "औसत ऑर्डर मूल्य",
    dailyTrend: "दैनिक बिक्री रुझान",
    paymentShare: "भुगतान मोड विभाजन",
    topSelling: "सबसे ज्यादा बिकने वाले वस्त्र",
    categoryShare: "श्रेणी वितरण",
    lowStockReport: "कम स्टॉक सूची",
    profitEstimation: "लाभ मार्जिन अनुमानक",
    profitEstimated: "अनुमानित लाभ (₹)"
  }
};

export type LanguageType = 'en' | 'hi';

export function getTranslation(lang: LanguageType) {
  return TRANSLATIONS[lang] || TRANSLATIONS.en;
}
